# Config / meta.yml
meta_title: "Tjenga"
meta_description: "Where kick-ass developers meet awesome clients."
meta_image: "tjenga.jpg"  # A picture in your app / assets / images /
twitter_account: "@nomdevotrecompte"  # essential for Twitter Cards
